config/routes.rb
Rails.application.routes.draw do
  resources :routes
  root 'pages#welcome'
  get 'order', to: 'routes#order'

  resources :users, except: [:new]
  get 'sign_up', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :routes
end

app/models/route.rb
class Route < ApplicationRecord
  has_and_belongs_to_many :orders

  validates :start, presence: true
  validates :finish, presence: true
  validates :departure, presence: true
  validates :arrival, presence: true
  validates :seats, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than: 0 }

  def self.departure_cities
    self.all.map {|route| route.start}.uniq
  end

  def self.arrival_cities
    self.all.map {|route| route.finish}.uniq
  end

  def departure_time
    departure.strftime("%m/%d/%y at %l:%M %p")
  end

  def arrival_time
    arrival.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :routes, through: :orders
  before_save { self.email = email.downcase }
  validates :name, presence: true,  
            uniqueness: { case_sensitive: false },
            length: {minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,  
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:new, :edit, :update, :destroy]

  def index
    @departure_cities = Route.departure_cities
    @arrival_cities = Route.arrival_cities
    if params[:departure_city]
      @routes = Route.where("start = ?", params[:departure_city])
    elsif params[:arrival_city]
      @routes = Route.where("finish = ?", params[:arrival_city])
    else
      @routes = Route.all
    end
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      flash[:success] = "Route was successfully created"
      redirect_to routes_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @route.update(route_params)
      flash[:success] = "Route was succesfully updated"
      redirect_to @route
    else
      render 'edit'
    end
  end

  def destroy
    @route.destroy
    flash[:danger] = "Route was deleted"
    redirect_to routes_path
  end

  def order
    if session[:user_id]
      @route = Route.find(params[:route])
      @user = User.find(session[:user_id])
      @order = Order.new
      @order.user = @user
      if @route.seats > 0
        @order.routes << @route
        @route.seats -= 1
        @route.save
        @order.save
        flash[:success] = "Youre order was created"
        redirect_to routes_path
      else
        flash[:danger] = "Sorry, there is no free seats"
        redirect_to routes_path
      end
    else
      flash[:danger] = "You have to log in"
      redirect_to login_path
    end
  end

  private

  def route_params
    params.require(:route).permit(:start, :finish, :departure, :arrival, :price, :seats)
  end

  def set_route
    @route = Route.find(params[:id])
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin can perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to routes_path
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy, :show]
  before_action :require_admin, only: [:index, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User was successfully created"
      redirect_to routes_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "User was successfully destroyed"
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "It's not your profile"
      redirect_to root_path
    end
  end
  
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin can perform this action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-12">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'iBus', routes_path, class: 'navbar-brand'
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if logged_in?
          li
            = link_to 'Log out', logout_path, method: :delete 
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
              | Actions
              span.caret
            ul.dropdown-menu
              - if current_user.admin?
                li
                  = link_to 'Create new route', new_route_path
              li
                = link_to 'Edit profile', edit_user_path(current_user)
              li
                = link_to 'Your orders', current_user
              li
                = link_to 'Users', users_path
              li.divider role="separator" 
              li
                a href="#"  Separated link
        - else
          li
            = link_to 'Log in', login_path
          li
            = link_to 'Sign up', sign_up_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ibus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navigation'%>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/welcome.html.slim
.jumbotron
  h1 iBus
  p We help you to find a cheap bus tickets
  p
    = link_to 'Routes', routes_path, class: "btn btn-primary btn-lg"
    

app/views/routes/_form.html.slim
= render 'shared/errors', obj: @route
= form_for(@route, :html => {class: "form-horizontal" }) do |f|
  .form-group
    = f.label :start, class: "col-sm-2 control-label"
    .col-sm-6  
      = f.text_field :start, class: "form-control"
  .form-group
    = f.label :finish, class: "col-sm-2 control-label"
    .col-sm-6  
      = f.text_field :finish, class: "form-control"
  .form-group
    = f.label :departure, class: "col-sm-2 control-label"
    .col-sm-6  
      = f.datetime_field :departure, class: "form-control"
  .form-group
    = f.label :arrival, class: "col-sm-2 control-label"
    .col-sm-6  
      = f.datetime_field :arrival, class: "form-control"
  .form-group
    = f.label :price, class: "col-sm-2 control-label"
    .col-sm-6  
      = f.number_field :price, class: "form-control"
  .form-group
    = f.label :Seats, class: "col-sm-2 control-label"
    .col-sm-6  
      = f.number_field :seats, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"
      = ' '
      = link_to "Cancel", routes_path, class: "btn btn-default"

app/views/routes/edit.html.slim
.panel.panel-default
  .panel-heading Edit route
  .panel-body
    = render 'form'

app/views/routes/index.html.slim
.panel.panel-default
  .panel-heading Welcome to iBus
  .panel-body
    p
      |
        Praesent bibendum a nunc vitae tempus. In aliquet urna vitae elementum
        pretium. Aliquam eu venenatis risus, vel sodales justo. Suspendisse eget
        lacus urna. Aliquam auctor magna ornare lorem ornare, nec volutpat
        tortor consectetur. Interdum et malesuada fames ac ante ipsum primis in
        faucibus. Vivamus vitae odio feugiat est vehicula pretium at a odio.
        Nulla auctor ipsum enim. Morbi vestibulum lectus ac purus pulvinar, sed
        finibus nisl imperdiet. Nullam laoreet mauris nisl, ut vehicula est
        aliquet bibendum. Nulla tristique rutrum arcu sit amet interdum. Nunc
        blandit tristique tincidunt. Aenean tincidunt justo massa,
        vitae condimentum nisl interdum sed.

h3 Available routes
hr
.filter-items
  .col-sm-6
    strong Departure from:
    - @departure_cities.each do |city|
      = link_to city, routes_path(departure_city: city), class: 'btn btn-xs btn-default'
  .col-sm-6
    strong Arrival to:
    - @arrival_cities.each do |city|
      = link_to city, routes_path(arrival_city: city), class: 'btn btn-xs btn-default'
    = link_to 'Clear filter', routes_path, class: "pull-right"
br
hr
table.table.table-condensed.table-hover
  thead
    tr
      th Route
      th Departure
      th Arrival
      th Seats
      th Price
  tbody
  - @routes.each do |route|
    tr
      td
        = link_to "#{route.start} - #{route.finish}", route
      td= route.departure_time
      td= route.arrival_time
      td= route.seats
      td= route.price
      td
        = link_to 'Show', route, class: 'btn btn-success btn-xs'
      - if logged_in? && current_user.admin?
        td
          = link_to 'Edit', edit_route_path(route), class: 'btn btn-warning btn-xs'
        td
          = link_to 'Delete', route, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger btn-xs'

app/views/routes/new.html.slim
.panel.panel-default
  .panel-heading New route
  .panel-body
    = render 'form'

app/views/routes/order.html.slim
p= @route.inspect
p= @order.routes.inspect
p= @user.inspect

app/views/routes/show.html.slim
.well
  = "#{@route.start} - #{@route.finish}"
dl.dl-horizontal
  dt From
  dd= @route.start
  hr
  dt To
  dd= @route.finish
  hr
  dt Departure
  dd= @route.departure
  hr
  dt Arrival
  dd= @route.arrival
  hr
  dt Price
  dd= @route.price
  hr
  dt Free seats available
  dd= @route.seats

= link_to 'Book now', order_path(route: @route.id), class: 'btn btn-success btn-block btn-lg '

app/views/shared/_errors.html.slim
- if obj.errors.any?
  .row
    .col-xs-8.col-xs-offset-2
      .panel.panel-danger
        .panel-heading
          h2 class=("panel-title")
            = pluralize(obj.errors.count, "error")
              prohibited this article from being saved:
          .panel-body
            ul
              - obj.errors.full_messages.each do |msg|
                li
                  = msg

app/views/users/_form.html.slim
= render 'shared/errors', obj: @user
.row
  .col-xs-12
    = form_for(@user, :html => {class: "form-horizontal"}, role: 'form') do |f|
      .form-group
        .control-label.col-sm-2
          = f.label :name
        .col-sm-8
          = f.text_field :name, class: "form-control", placeholder: "Enter username", autofocus: true
      .form-group
        .control-label.col-sm-2
          = f.label :email
        .col-sm-8
          = f.email_field :email, class: "form-control", placeholder: "Enter email"
      .form-group
        .control-label.col-sm-2
          = f.label :password
        .col-sm-8
          = f.password_field :password, class: "form-control", placeholder: "Enter password"
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit(@user.new_record? ? 'Sign up' : 'Update user', class: "btn btn-primary")
          = ' '
          = link_to "Cancel", routes_path, class: "btn btn-default"

app/views/users/edit.html.slim
h2 Edit youre profile
= render 'form', obj: @user

app/views/users/index.html.slim
h2 Users

table.table.table-condensed.table-hover
  thead
    tr
      th Name
      th Email
      th Orders
      th Totall
  tbody
  - @users.each do |user|
    tr
      td
        = link_to "#{user.name}", user
      td= user.email
      td= user.orders.count
      td
      td
        = link_to 'Show', user, class: 'btn btn-success btn-xs'
      td
        = link_to 'Edit', edit_user_path(user), class: 'btn btn-warning btn-xs'
      td
        = link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger btn-xs'

app/views/users/new.html.slim
h2 Sign up
= render 'form'

app/views/users/show.html.slim
.panel.panel-default
  .panel-heading = "Hello, #{@user.name}!"
  .panel-body
    dl.dl-horizontal
      dt Name
      dd= @user.name
      dt Email
      dd= @user.email
    table.table
      thead
        th Order id
        th Route
        th Date
        th Totall
      tbody
      - @user.orders.each do |order|
        - order.routes.each do |route|
          tr
            td= order.id
            td= "#{route.start} - #{route.finish}"
            td= order.created_at
            td= route.price
          / td= "#{route.start} - #{route.finish}"